services:
  drinkarr:
    image: ghcr.io/channelcat/drinkarr:latest
    environment:
      - ANTHROPIC_API_KEY
      - MY_API_FILMS_TOKEN
      - OPENSUBTITLES_API_KEY
      - OPENSUBTITLES_USERNAME
      - OPENSUBTITLES_PASSWORD
    ports:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.drinkarr.rule=Host(`drinkarr.hill.tools`)
      - traefik.http.routers.drinkarr.entrypoints=web,websecure
      - traefik.http.routers.drinkarr.tls.certresolver=letsencrypt
    networks:
      - webserver_web
  cache:
    image: redis:alpine
    ports:
      - 6379
networks:
  webserver_web:
    external: true
