services:
    couchquest:
        image: ghcr.io/channelcat/couchquest:latest
        environment:
            - ENV=production
            - CONFIG_PRIVATE_KEY
        ports:
            - 80
        labels:
            - traefik.enable=true
            - traefik.http.routers.couchquest.rule=Host(`couchquest.app`)
            - traefik.http.routers.couchquest.entrypoints=web,websecure
            - traefik.http.routers.couchquest.tls.certresolver=letsencrypt
        networks:
            - webserver_web
    cache:
        image: redis:alpine
        ports:
            - 6379
networks:
    webserver_web:
        external: true
