config:
  anthropic_api_key.encrypted: !!binary |
    WmhUejlWdVgvYXdBK0UvUjA0c1hGNmZLcWx2dlhwaFM0c3hrVUVtV3kveWYrZ2F4SkYraFEwWDlX
    N0kyYVdEclprWkR5dWp2dllMOUVQNjJkRkZLeWVzV3BWZVYzT2NtMDhtd00yTkRjcUNOS090Y0k5
    Q1BXR2RzVy9PdFplOFpGTm5OMWx2S2lTOFF2YUM3M1V6R3RvMk9GMkVudG12RTdtY1ZWWFJRRHR3
    c0V0dEo2VnFTelBTMGxUK0R3dHVmTThiYzdJa1JKRytRVVY4SVZTTGZoRE0ya2FGS0tRQnAyenBl
    Y0RISjgvK0crcUlLRjlka1FCaWpJRmdnSDJsbWk5RXlmbk0xem41bVlNNkdhd2lCT2wxd2x4NlJI
    dlAwWVNkanZVelp5c2FzUFpYU0FmUFMrSTQ4Zkh4Yy9vZ1c2TmRtSFVqSVdFTEE2cFl3TWc1ZFFn
    PT0=
  google_client_id: 100000000000000000000
  google_client_secret: 100000000000000000000
  google_redirect_uri: http://localhost:8000/auth/google/callback
  my_api_films_token.encrypted: !!binary |
    Wnl2aUV1bnRHN21TblVmY3NEZTlYWmJxMFdHWVc5enVmblBpZHFXRXM5NmRkUU8rVFplV3pmdVhP
    cGl2WTVOVVJnT3oyaTJETGRjemRtSjl0cG92Z1pJclM5L29Ja3gvdFNTUks4ZkRLNmd1K2wxV0Qr
    S3ZUbGlwMHpWRklNZWRjbnpJVXhXQkc1cExOR1pQVlIxVFBBL2s3VEV3bmdMbU1lSmlZRE5LdzlQ
    UURmV2Jmb0pYekE1MHUyS3d3dWx1eVh1YzFFQVdZRDRkZzRTZVhtZ3QwdEVWTVdjNG4rMmY0dGs3
    eDkxamJOaC9ZbmFSTkdrc3BSbWFWRi9ubHBFNlRzQWVkL2sxcHU1K2JwY29aR2xPeEdHZlY3ZENL
    OGFpcXd5ZTdndWJyYUZ4NitoZWJEZzlyUWQxSHBVYUVxSXlPRnltMDVUYlc3bWYzaVNLaUdIeEln
    PT0=
  opensubtitles_api_key.encrypted: !!binary |
    a3lzRzJZL2xkN0ZJWjkrbVZaMXljZnB1QlllcjdDSXJaSnI3RitCOUc4Nm11TEM0NEVwU0JnTW5o
    TDJFMFhSQzdLKzRzancrS1BjSlVaZ3Z1aXZkK1JlbGRTblRrdVFNR0lZdU1Gek1laThUWGNjWkhz
    WEVubW5rZzlKVW9FNWlEeThJOGxJVGtpSkZDTHNYc1MyQ3E5Y1BseUxRR2wwV2FKWXhZOHphcWEz
    T3hhUXBLdnFtNFdFcDIzRld3SC95Y01kMmxvVDJZZDBhemV3RmNpVmh3bnBNdGYvSklpdG9hTU53
    cjZKcms5eVdaSjJhYmd1NEhleGR5dmh4bllkaDBKS0NMdjVvSmdJemdFRENudVR4dFhJSHAyZ2xt
    cnBreEN4RVJUeWRXVlRJNmo5RFNmNnpZeUhYWXRUMXJDK0FDc2ZJaDE0YjU3bXRGWUR0N3FmOWd3
    PT0=
  opensubtitles_password.encrypted: !!binary |
    aFhKblFEOCtubHdwUmJ1dThFYkxhU3ZKZmpqY0pTTzlMTVpZVjMxbHZLbmRLLytJQjlPTjhHR2Jv
    SWdmdmYvaVUwM09aN2xLVWJUak1IZHdiR0pYejQ2SFJwUDFBeUdLSzZTaktRcmZsTlJIN1k5Q2ZH
    bGhReDlmaFJuQlBneFJ0TGJZNWFnaU82Wkh2UnRjY1BGUWNoSWVHRnYwTy8ySjhlSHFXZk8zTktM
    V2dFOERNQVRrdFVleUhRNXF3VlV2VWQ4UTlYR251dzhvS1hucFNnNVl3eFA0Mk9HdGJFSThCa2Q1
    RGE1dHYyU3NsbHN4UEZjQmhnNDY4aUh4WkZLZjFnOElHSDNTWnRoRW82dUsyZEtXdmJnU0F0ZzRx
    RnRsSzMxL1ZITXNNTnBtNi9GNmFWRHBobzlUUGZDWEN3U3UvQ0lxcE02Sm5BUkQycjVVQ2NUN3dR
    PT0=
  opensubtitles_username: channelcat
  youtube_api_key.encrypted: !!binary |
    ajhNY2EyS0dMOVhvTXlPTTV0ZGRmcThJV2tyaVgrdUNlUUYwQ1dhdkt1QTBVTEd0S0xDNmRCT2F6
    Y2dBQ3grS3RtZzdmdTNFOEZqSWVvSUlvUEFaelUxRm8wT2NzaldPalMzRmIwOU1JcU8wZm9GQ3VL
    WDFkRTNQMUltSE1FZHcyWGhKWnl5TWdJSUZORGE4TkU2dDdHNVhtdTJBNWlrV0RXd25MdkN0emt1
    dWdBK0FVeDJjU2tnMzhuOEFWVVNlUy9STmM0MVFDZkZkWmVxQjNQL21oUmJOdFExRzBiQXNzbkJn
    Zmw1b0dPZjUvT25JaFkrMjRtQTI2VXZVdWZWTWlOQ0JlU0VlUGlGUTlWYnNjNjk2RllrWi9tTVdF
    NERVa3dGNjFLT1hoQ205OU15YlRKSVY0YzZ5bkxYYjMrUDB5cWRPVUtlaUdRRng5N1BBK0lJMmZR
    PT0=
  youtube_proxy: http://proxy:8888
encryption:
  key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXBwaVQrZWdBV3hGalE0bHNTUlpoN1pjMW56cDlFakhQQjZRNzh6MFBkZ0Nzc1RvbkNneGoKb3lXakFXZ3NpSmd3NDhnWXo3OUxUWndlVngyQnVGVWhSS2hFcTRHcjJudWx3OXNiOEFDTkVHeU9vODdXdDdKRAphMFRQN3lzQU1PZ0p6OXdKT285bC91QmFGSXRyUXVYVzduS3RlcDV1dnJhdHlNdnNQd3VMdTFsbVlsUTBrdUEzCmV2QTYyTFVWcnRBelV6N3F2eHFqTGJuMjBiSDA5T0N5L0hqNDJ6MzJWQllIaWxDc0pEL0hydlNVeGZ5VTh2WWoKVmgwZUFBM01WdzhDR2E5cmh2RE9uc3I4bkgzT210L25KWncrc1JDWU1QR2FKS05TUzQ1U1BRZkhBdFBOWlZaWgp1VU9rbkxtK0gycXh4VFZZdWUxdE92aDNRdTdEWGk0cXBRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
env:
  production:
    config:
      database_host: db
      database_name: couchquest
      database_user: couchquest_user
      database_password: 7eleven-was-a-part-time-job
  development:
    config:
      database_host: db
      database_name: couchquest
      database_user: couchquest_user
      database_password: 7eleven-was-a-part-time-job
