name: Deploy Main Branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Build base'
        run: docker build -t ghcr.io/channelcat/drinkarr:latest .
        # GITHUB_TOKEN is built-in
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: 'Push to GHCR'
        run: docker push ghcr.io/channelcat/drinkarr:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_HOST: "ssh://ec2-user@webserver.hill.tools"
      DOCKER_SSH_KEY: ${{ secrets.DOCKER_SSH_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: nightstory/setup-docker-remote@v1
        with:
          ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
          ssh_host_user: ec2-user
          ssh_host: webserver.hill.tools
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: 'Pull Compose'
        run: docker compose -f docker-compose.deploy.yml pull
      - name: 'Deploy compose'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          MY_API_FILMS_TOKEN: ${{ secrets.MY_API_FILMS_TOKEN }}
          OPENSUBTITLES_API_KEY: ${{ secrets.OPENSUBTITLES_API_KEY }}
          OPENSUBTITLES_USERNAME: ${{ secrets.OPENSUBTITLES_USERNAME }}
          OPENSUBTITLES_PASSWORD: ${{ secrets.OPENSUBTITLES_PASSWORD }}
        run: docker compose -f docker-compose.deploy.yml up -d
